version: "3.8"

services:
  tweet-optimizer-backend:
    build: 
      context: ./backend
    ports:
      - "8001:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - tweet-optimizer-network

  tweet-optimizer-frontend:
    build:
      context: ./frontend
    ports:
      - "3001:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - tweet-optimizer-backend
    restart: unless-stopped
    networks:
      - tweet-optimizer-network

  tweet-optimizer-nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./conf/nginx/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ./ssl
        target: /etc/nginx/ssl
      - type: bind
        source: ./conf/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - tweet-optimizer-frontend
      - tweet-optimizer-backend
    restart: unless-stopped
    networks:
      - tweet-optimizer-network

networks:
  tweet-optimizer-network:
    name: tweet-optimizer-network 