version: "3.8"

services:
  tweet-optimizer-backend:
    build: 
      context: ./backend
      target: development
    ports:
      - "8001:8000"
    volumes:
      - type: bind
        source: ./backend
        target: /app/backend
    environment:
      - PYTHONPATH=/app
    env_file:
      - ./backend/.env.development
    networks:
      - tweet-optimizer-network

  tweet-optimizer-frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "3001:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env.development
    depends_on:
      - tweet-optimizer-backend
    networks:
      - tweet-optimizer-network

  tweet-optimizer-nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./conf/nginx/conf.d/default.dev.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./conf/nginx/nginx.dev.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - tweet-optimizer-frontend
      - tweet-optimizer-backend
    networks:
      - tweet-optimizer-network

networks:
  tweet-optimizer-network:
    name: tweet-optimizer-network 